# ./include/BUILD
cc_library(
  name = "base_node",
  hdrs = ["BaseBinaryNode.hpp"],
  visibility = ["//visibility:public"]
)

cc_library(
  name = "node",
  hdrs = ["BinarySearchTreeNode.hpp"],
  visibility = ["//visibility:public"]
)

cc_library(
  name = "bstree",
  hdrs = ["BSTree.hpp"],
  visibility = ["//visibility:public"]
)
