# ./include/BUILD
cc_library(
  name = "node",
  hdrs = ["Node.hpp"],
  visibility = ["//visibility:public"]
)

cc_library(
  name = "bstree",
  hdrs = ["BSTree.hpp"],
  visibility = ["//visibility:public"]
)
